// flow-typed signature: f2b4704c8cd711fcfdb7fc73da13ab56
// flow-typed version: <<STUB>>/babel-preset-react_v^6.11.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-react/index' {
  declare module.exports: $Exports<'babel-preset-react'>;
}
declare module 'babel-preset-react/index.js' {
  declare module.exports: $Exports<'babel-preset-react'>;
}
