// flow-typed signature: 0d4ba98c3a5f8191c808c322488c6e27
// flow-typed version: <<STUB>>/expose-loader_v^0.7.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expose-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'expose-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'expose-loader/index' {
  declare module.exports: $Exports<'expose-loader'>;
}
declare module 'expose-loader/index.js' {
  declare module.exports: $Exports<'expose-loader'>;
}
