// flow-typed signature: 203e7d4cc9edbffd8bb5445135741bae
// flow-typed version: <<STUB>>/lodash.sortby_v^4.7.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.sortby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.sortby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.sortby/index' {
  declare module.exports: $Exports<'lodash.sortby'>;
}
declare module 'lodash.sortby/index.js' {
  declare module.exports: $Exports<'lodash.sortby'>;
}
