// flow-typed signature: c5425748cea22111aa35dfd3e5e7b035
// flow-typed version: <<STUB>>/react-base16-styling_v^0.4.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-base16-styling'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-base16-styling' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-base16-styling/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-base16-styling/lib/index.js' {
  declare module.exports: $Exports<'react-base16-styling/lib/index'>;
}
