export default [
  { label: 'No Country', text: '', value: null, static: true },
  null,
  { text: 'Disabled Option', disabled: true, static: true },
  null,
  { text: 'Afghanistan', value: 'value--Afghanistan' },
  { text: 'Albania', value: 'value--Albania' },
  { text: 'Algeria', value: 'value--Algeria' },
  { text: 'Andorra', value: 'value--Andorra' },
  { text: 'Angola', value: 'value--Angola' },
  { text: 'Antigua & Deps', value: 'value--Antigua & Deps' },
  { text: 'Argentina', value: 'value--Argentina' },
  { text: 'Armenia', value: 'value--Armenia' },
  { text: 'Australia', value: 'value--Australia' },
  { text: 'Austria', value: 'value--Austria' },
  { text: 'Azerbaijan', value: 'value--Azerbaijan' },
  { text: 'Bahamas', value: 'value--Bahamas' },
  { text: 'Bahrain', value: 'value--Bahrain' },
  { text: 'Bangladesh', value: 'value--Bangladesh' },
  { text: 'Barbados', value: 'value--Barbados' },
  { text: 'Belarus', value: 'value--Belarus' },
  { text: 'Belgium', value: 'value--Belgium' },
  { text: 'Belize', value: 'value--Belize' },
  { text: 'Benin', value: 'value--Benin' },
  { text: 'Bhutan', value: 'value--Bhutan' },
  { text: 'Bolivia', value: 'value--Bolivia' },
  { text: 'Bosnia Herzegovina', value: 'value--Bosnia Herzegovina' },
  { text: 'Botswana', value: 'value--Botswana' },
  { text: 'Brazil', value: 'value--Brazil' },
  { text: 'Brunei', value: 'value--Brunei' },
  { text: 'Bulgaria', value: 'value--Bulgaria' },
  { text: 'Burkina', value: 'value--Burkina' },
  { text: 'Burundi', value: 'value--Burundi' },
  { text: 'Cambodia', value: 'value--Cambodia' },
  { text: 'Cameroon', value: 'value--Cameroon' },
  { text: 'Canada', value: 'value--Canada' },
  { text: 'Cape Verde', value: 'value--Cape Verde' },
  { text: 'Central African Rep', value: 'value--Central African Rep' },
  { text: 'Chad', value: 'value--Chad' },
  { text: 'Chile', value: 'value--Chile' },
  { text: 'China', value: 'value--China' },
  { text: 'Colombia', value: 'value--Colombia' },
  { text: 'Comoros', value: 'value--Comoros' },
  { text: 'Congo', value: 'value--Congo' },
  { text: 'Congo {Democratic Rep}', value: 'value--Congo {Democratic Rep}' },
  { text: 'Costa Rica', value: 'value--Costa Rica' },
  { text: 'Croatia', value: 'value--Croatia' },
  { text: 'Cuba', value: 'value--Cuba' },
  { text: 'Cyprus', value: 'value--Cyprus' },
  { text: 'Czech Republic', value: 'value--Czech Republic' },
  { text: 'Denmark', value: 'value--Denmark' },
  { text: 'Djibouti', value: 'value--Djibouti' },
  { text: 'Dominica', value: 'value--Dominica' },
  { text: 'Dominican Republic', value: 'value--Dominican Republic' },
  { text: 'East Timor', value: 'value--East Timor' },
  { text: 'Ecuador', value: 'value--Ecuador' },
  { text: 'Egypt', value: 'value--Egypt' },
  { text: 'El Salvador', value: 'value--El Salvador' },
  { text: 'Equatorial Guinea', value: 'value--Equatorial Guinea' },
  { text: 'Eritrea', value: 'value--Eritrea' },
  { text: 'Estonia', value: 'value--Estonia' },
  { text: 'Ethiopia', value: 'value--Ethiopia' },
  { text: 'Fiji', value: 'value--Fiji' },
  { text: 'Finland', value: 'value--Finland' },
  { text: 'France', value: 'value--France' },
  { text: 'Gabon', value: 'value--Gabon' },
  { text: 'Gambia', value: 'value--Gambia' },
  { text: 'Georgia', value: 'value--Georgia' },
  { text: 'Germany', value: 'value--Germany' },
  { text: 'Ghana', value: 'value--Ghana' },
  { text: 'Greece', value: 'value--Greece' },
  { text: 'Grenada', value: 'value--Grenada' },
  { text: 'Guatemala', value: 'value--Guatemala' },
  { text: 'Guinea', value: 'value--Guinea' },
  { text: 'Guinea-Bissau', value: 'value--Guinea-Bissau' },
  { text: 'Guyana', value: 'value--Guyana' },
  { text: 'Haiti', value: 'value--Haiti' },
  { text: 'Honduras', value: 'value--Honduras' },
  { text: 'Hungary', value: 'value--Hungary' },
  { text: 'Iceland', value: 'value--Iceland' },
  { text: 'India', value: 'value--India' },
  { text: 'Indonesia', value: 'value--Indonesia' },
  { text: 'Iran', value: 'value--Iran' },
  { text: 'Iraq', value: 'value--Iraq' },
  { text: 'Ireland {Republic}', value: 'value--Ireland {Republic}' },
  { text: 'Israel', value: 'value--Israel' },
  { text: 'Italy', value: 'value--Italy' },
  { text: 'Ivory Coast', value: 'value--Ivory Coast' },
  { text: 'Jamaica', value: 'value--Jamaica' },
  { text: 'Japan', value: 'value--Japan' },
  { text: 'Jordan', value: 'value--Jordan' },
  { text: 'Kazakhstan', value: 'value--Kazakhstan' },
  { text: 'Kenya', value: 'value--Kenya' },
  { text: 'Kiribati', value: 'value--Kiribati' },
  { text: 'Korea North', value: 'value--Korea North' },
  { text: 'Korea South', value: 'value--Korea South' },
  { text: 'Kosovo', value: 'value--Kosovo' },
  { text: 'Kuwait', value: 'value--Kuwait' },
  { text: 'Kyrgyzstan', value: 'value--Kyrgyzstan' },
  { text: 'Laos', value: 'value--Laos' },
  { text: 'Latvia', value: 'value--Latvia' },
  { text: 'Lebanon', value: 'value--Lebanon' },
  { text: 'Lesotho', value: 'value--Lesotho' },
  { text: 'Liberia', value: 'value--Liberia' },
  { text: 'Libya', value: 'value--Libya' },
  { text: 'Liechtenstein', value: 'value--Liechtenstein' },
  { text: 'Lithuania', value: 'value--Lithuania' },
  { text: 'Luxembourg', value: 'value--Luxembourg' },
  { text: 'Macedonia', value: 'value--Macedonia' },
  { text: 'Madagascar', value: 'value--Madagascar' },
  { text: 'Malawi', value: 'value--Malawi' },
  { text: 'Malaysia', value: 'value--Malaysia' },
  { text: 'Maldives', value: 'value--Maldives' },
  { text: 'Mali', value: 'value--Mali' },
  { text: 'Malta', value: 'value--Malta' },
  { text: 'Marshall Islands', value: 'value--Marshall Islands' },
  { text: 'Mauritania', value: 'value--Mauritania' },
  { text: 'Mauritius', value: 'value--Mauritius' },
  { text: 'Mexico', value: 'value--Mexico' },
  { text: 'Micronesia', value: 'value--Micronesia' },
  { text: 'Moldova', value: 'value--Moldova' },
  { text: 'Monaco', value: 'value--Monaco' },
  { text: 'Mongolia', value: 'value--Mongolia' },
  { text: 'Montenegro', value: 'value--Montenegro' },
  { text: 'Morocco', value: 'value--Morocco' },
  { text: 'Mozambique', value: 'value--Mozambique' },
  { text: 'Myanmar, {Burma}', value: 'value--Myanmar, {Burma}' },
  { text: 'Namibia', value: 'value--Namibia' },
  { text: 'Nauru', value: 'value--Nauru' },
  { text: 'Nepal', value: 'value--Nepal' },
  { text: 'Netherlands', value: 'value--Netherlands' },
  { text: 'New Zealand', value: 'value--New Zealand' },
  { text: 'Nicaragua', value: 'value--Nicaragua' },
  { text: 'Niger', value: 'value--Niger' },
  { text: 'Nigeria', value: 'value--Nigeria' },
  { text: 'Norway', value: 'value--Norway' },
  { text: 'Oman', value: 'value--Oman' },
  { text: 'Pakistan', value: 'value--Pakistan' },
  { text: 'Palau', value: 'value--Palau' },
  { text: 'Panama', value: 'value--Panama' },
  { text: 'Papua New Guinea', value: 'value--Papua New Guinea' },
  { text: 'Paraguay', value: 'value--Paraguay' },
  { text: 'Peru', value: 'value--Peru' },
  { text: 'Philippines', value: 'value--Philippines' },
  { text: 'Poland', value: 'value--Poland' },
  { text: 'Portugal', value: 'value--Portugal' },
  { text: 'Qatar', value: 'value--Qatar' },
  { text: 'Romania', value: 'value--Romania' },
  { text: 'Russian Federation', value: 'value--Russian Federation' },
  { text: 'Rwanda', value: 'value--Rwanda' },
  { text: 'St Kitts & Nevis', value: 'value--St Kitts & Nevis' },
  { text: 'St Lucia', value: 'value--St Lucia' },
  { text: 'Saint Vincent & the Grenadines', value: 'value--Saint Vincent & the Grenadines' },
  { text: 'Samoa', value: 'value--Samoa' },
  { text: 'San Marino', value: 'value--San Marino' },
  { text: 'Sao Tome & Principe', value: 'value--Sao Tome & Principe' },
  { text: 'Saudi Arabia', value: 'value--Saudi Arabia' },
  { text: 'Senegal', value: 'value--Senegal' },
  { text: 'Serbia', value: 'value--Serbia' },
  { text: 'Seychelles', value: 'value--Seychelles' },
  { text: 'Sierra Leone', value: 'value--Sierra Leone' },
  { text: 'Singapore', value: 'value--Singapore' },
  { text: 'Slovakia', value: 'value--Slovakia' },
  { text: 'Slovenia', value: 'value--Slovenia' },
  { text: 'Solomon Islands', value: 'value--Solomon Islands' },
  { text: 'Somalia', value: 'value--Somalia' },
  { text: 'South Africa', value: 'value--South Africa' },
  { text: 'South Sudan', value: 'value--South Sudan' },
  { text: 'Spain', value: 'value--Spain' },
  { text: 'Sri Lanka', value: 'value--Sri Lanka' },
  { text: 'Sudan', value: 'value--Sudan' },
  { text: 'Suriname', value: 'value--Suriname' },
  { text: 'Swaziland', value: 'value--Swaziland' },
  { text: 'Sweden', value: 'value--Sweden' },
  { text: 'Switzerland', value: 'value--Switzerland' },
  { text: 'Syria', value: 'value--Syria' },
  { text: 'Taiwan', value: 'value--Taiwan' },
  { text: 'Tajikistan', value: 'value--Tajikistan' },
  { text: 'Tanzania', value: 'value--Tanzania' },
  { text: 'Thailand', value: 'value--Thailand' },
  { text: 'Togo', value: 'value--Togo' },
  { text: 'Tonga', value: 'value--Tonga' },
  { text: 'Trinidad & Tobago', value: 'value--Trinidad & Tobago' },
  { text: 'Tunisia', value: 'value--Tunisia' },
  { text: 'Turkey', value: 'value--Turkey' },
  { text: 'Turkmenistan', value: 'value--Turkmenistan' },
  { text: 'Tuvalu', value: 'value--Tuvalu' },
  { text: 'Uganda', value: 'value--Uganda' },
  { text: 'Ukraine', value: 'value--Ukraine' },
  { text: 'United Arab Emirates', value: 'value--United Arab Emirates' },
  { text: 'United Kingdom', value: 'value--United Kingdom' },
  { text: 'United States', value: 'value--United States' },
  { text: 'Uruguay', value: 'value--Uruguay' },
  { text: 'Uzbekistan', value: 'value--Uzbekistan' },
  { text: 'Vanuatu', value: 'value--Vanuatu' },
  { text: 'Vatican City', value: 'value--Vatican City' },
  { text: 'Venezuela', value: 'value--Venezuela' },
  { text: 'Vietnam', value: 'value--Vietnam' },
  { text: 'Yemen', value: 'value--Yemen' },
  { text: 'Zambia', value: 'value--Zambia' },
  { text: 'Zimbabwe', value: 'value--Zimbabwe' }
];
